### ISSUE TITLE
Check if simulator is running

### ISSUE THREAD

**Issue by Hither1** [learn-to-race/l2r#12]
<img width="1404" alt="Screenshot 2022-06-23 at 4 13 34 PM" src="https://user-images.githubusercontent.com/42910536/175391293-51f344f4-36ca-4491-b6ac-fe71afd02f57.png">
Hi,

I'm trying to run Learn-to-race in the offscreen mode in a Centos system. I'm seeing this (as attached picture) in my terminal. I'm not sure if the simulator is correctly running. Can someone help? Thanks

**Comment by hermgerm29** [comment]
Thanks for raising this issue - we're actually working on a significant update to this repository, Part of this update will be integration tests with the simulator so that you can validate that the various interfaces are working appropriately which is particularly useful in offscreen mode.
