### ISSUE TITLE
Examples are broken, unable to get camera feed

### ISSUE THREAD

**Issue by XDynames** [learn-to-race/l2r#6]
Hey guys,

I have been hammering away on building up a training framework around your interface with the simulator and some of the recent changes have broken most of the examples you provide in the repository and what seems like the ability for observations to be received.

I have updated configs to include missing keys but I am still getting black images out as observations with the camera's `_receive()` thread blocking at `rawbuf = self.sock.recv(0)`. I believe this means that the simulator is not sending anything via that socket despite it being enables and connected to.

Any help would be much appreciated, can't really race without being able to see

**Comment by hermgerm29** [comment]
Hello,

We have been able to reproduce the issue, but we believe the problem is with the Arrival simulator `0.7.1*`. We recommend downgrading to `0.7.0*` for now.

**Comment by jonfranc** [comment]
It is possible to access version 0.7.0* of the simulator, via: https://www.aicrowd.com/clef_tasks/82/task_dataset_files?challenge_id=954 (requires creating an AICrowd account)

**Comment by goforks12** [comment]
everytime i try to do an example sac train. My computer has to shut down immediatly. Im doing this on Ubuntu on windows.
